checkov and sarif updated

diff --git a/.github/actions/terraform-ci/action.yml b/.github/actions/terraform-ci/action.yml
--- a/.github/actions/terraform-ci/action.yml
+++ b/.github/actions/terraform-ci/action.yml
@@ -41,9 +41,28 @@ runs:
       run: |
         pip install checkov
 
-    - name: Run Checkov
-      shell: bash
-      run: checkov -d ./terraform
+    # - name: Run Checkov
+    #   shell: bash
+    #   run: checkov -d ./terraform
+
+    - name: Run Checkov action
+      uses: bridgecrewio/checkov-action@master
+      with:
+        directory: ./terraform
+        output_format: cli,sarif
+        output_file_path: console,results.sarif
+        
+    - name: Upload SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+        
+      # Results are generated only on a success or failure
+      # this is required since GitHub by default won't run the next step
+      # when the previous one has failed. Security checks that do not pass will 'fail'.
+      # An alternative is to add `continue-on-error: true` to the previous step
+      # Or 'soft_fail: true' to checkov.
+      if: success() || failure()
+      with:
+        sarif_file: results.sarif
 
     # - name: Setup SonarQube
     #   shell: bash
