environment added

diff --git a/.github/workflows/tf-ci.yml b/.github/workflows/tf-ci.yml
--- a/.github/workflows/tf-ci.yml
+++ b/.github/workflows/tf-ci.yml
@@ -1,23 +1,24 @@
 name: Terraform CI
 
 on:
-  push:
-    branches:
-      - develop
-      - main
+  workflow_dispatch:
+  # push:
+  #   branches:
+  #     - develop
+  #     - main
 
 jobs:
-  terraform_ci:
+  terraform_ci_dev:
     runs-on: ubuntu-latest
+    environment: DEV
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
 
     - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v1
-      with:
-        terraform_version: '0.13'  # Use the desired version (e.g., 0.13, 0.14, 1.0, etc.)
+      uses: hashicorp/setup-terraform@v2
+      
 
     - name: Terraform Format
       id: fmt
@@ -40,3 +41,44 @@ jobs:
     - name: Allow PR Merge on Success
       if: ${{ success() }}
       run: echo "CI checks passed. You can merge the PR now."
+
+
+  
+  terraform_ci_qa:
+    runs-on: ubuntu-latest
+    environment: QA
+    needs: terraform_ci_dev
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: Run a script
+      run: |
+        echo 'Hello {{ secrets.TF_API_TOKEN }}
+
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
+      
+
+    - name: Terraform Format
+      id: fmt
+      run: terraform fmt -check
+
+    - name: Terraform Init
+      id: init
+      run: terraform init
+    
+    - name: Terraform Validate
+      id: validate
+      run: terraform validate
+
+    # If the CI fails, block merging the PR
+    - name: Block PR Merge on Failure
+      if: ${{ failure() }}
+      run: echo "CI checks failed. Please fix the issues before merging." && exit 1
+
+    # If the CI passes, enable merging the PR
+    - name: Allow PR Merge on Success
+      if: ${{ success() }}
+      run: echo "CI checks passed. You can merge the PR now."
+    
